languageCode = "en-us"
title = "Hugo"
baseURL = "https://gohugo.netlify.com/"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
theme = "gohugo"
paginate =                    20
#paginatePath =                "page"

[params]
  logo = "/images/hugo-logo_opt-500x137.png"
  description = "The world’s fastest framework for building websites"
  map_link = "https://www.google.com/maps/place/Civic+Hall/@40.742284,-73.9962257,17z/data=!3m1!4b1!4m5!3m4!1s0x89c259a3a3340f3d:0xba4060a01c13cc2a!8m2!3d40.74228!4d-73.994037"

  ## Gh repo for site footer (include trailing slash)
 github_hrepo = "https://github.com/spf13/hugo/"
 ## GitHub Docs Repository Base URL (include trailing slash)
 ### https://github.com/spf13/hugo/tree/master/docs
 ### Edit content repo (set to automatically enter "edit" mode => good for "improve this page" links)
 github_docs_repo = "https://github.com/rdwatters/hugo-docs-concept/edit/master/"
 ## Gitter URL
 gitter = "https://gitter.im/spf13/hugo"
 ## Discuss Forum URL
 forum = "https://discuss.gohugo.io"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"


[[menu.home]]
  name = "Docs"
  weight = 1
  identifier = "docs"
  url = "http://gohugo.io/overview/introduction/"


[[menu.home]]
  name = "Community"
  weight = 10
  identifier = "community"
  url = "https://discuss.gohugo.io/"

[[menu.home]]
  name = "Themes"
  weight = 15
  identifier = "themes"
  url = "http://themes.gohugo.io/"

[[menu.home]]
  name = "Github"
  weight = 15
  identifier = "github"
  url = "https://github.com/spf13/hugo"

[[menu.home]]
  name = "News"
  weight = 100
  identifier = "news"
  url = "/news/"
